version: '3.1'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo-development
    volumes:
      - postgres-data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        "-source",
        "file:///migrations",
        "-database",
        "postgres://postgres:password@db:5432/todo-development?sslmode=disable",
        "up"
      ]
    links:
      - db

volumes:
  postgres-data:
    driver: local
